# Generated by Django 3.0 on 2019-12-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='show',
            fields=[
                ('Longitude', models.FloatField()),
                ('Latitude', models.FloatField()),
                ('Unique_squirrel_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], max_length=2)),
                ('Date', models.DateField()),
                ('Age', models.CharField(blank=True, max_length=20, null=True)),
                ('Primary_fur_color', models.CharField(blank=True, max_length=30, null=True)),
                ('Location', models.CharField(blank=True, max_length=50, null=True)),
                ('Specific_location', models.CharField(blank=True, max_length=50, null=True)),
                ('Running', models.BooleanField()),
                ('Chasing', models.BooleanField()),
                ('Climbing', models.BooleanField()),
                ('Eating', models.BooleanField()),
                ('Foraging', models.BooleanField()),
                ('Other_activities', models.CharField(blank=True, max_length=80, null=True)),
                ('Kuks', models.BooleanField()),
                ('Quaas', models.BooleanField()),
                ('Moans', models.BooleanField()),
                ('Tail_flags', models.BooleanField()),
                ('Tail_twitches', models.BooleanField()),
                ('Approaches', models.BooleanField()),
                ('Indifferent', models.BooleanField()),
                ('Runs_from', models.BooleanField()),
            ],
        ),
    ]
